version: '3'
services:
  db:
    image: postgres
    env_file:
      - ./backend/.env # This line tells Docker Compose to use variables from .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
